//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebPage.LocalService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrinterArea", Namespace="http://schemas.datacontract.org/2004/07/LabelGeneratorLib")]
    public enum PrinterArea : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        smt = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        in_process = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        baseplate = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        final = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        aspinv = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        wherehouse = 151,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabelTypes", Namespace="http://schemas.datacontract.org/2004/07/LabelGeneratorLib")]
    public enum LabelTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        none = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        small = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        large = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        both = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cable = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        type_a = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        aspinv = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        philips_small = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        philips_large = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        philips_packing = 50,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalService.ILabelGenerator")]
    public interface ILabelGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelGenerator/Print", ReplyAction="http://tempuri.org/ILabelGenerator/PrintResponse")]
        bool Print(TestWebPage.LocalService.PrinterArea eArea, TestWebPage.LocalService.LabelTypes eLabelType, string[] sColumns, string sTemplate, int nQty, int nStartPos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelGenerator/AddPrintJob", ReplyAction="http://tempuri.org/ILabelGenerator/AddPrintJobResponse")]
        int AddPrintJob(TestWebPage.LocalService.PrinterArea eArea, TestWebPage.LocalService.LabelTypes eLabelType, string[] sColumns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelGenerator/AddDataRow", ReplyAction="http://tempuri.org/ILabelGenerator/AddDataRowResponse")]
        bool AddDataRow(int nJobNumber, string[] sData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelGenerator/AddDataRowFromDB", ReplyAction="http://tempuri.org/ILabelGenerator/AddDataRowFromDBResponse")]
        bool AddDataRowFromDB(string[] sSerials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelGenerator/AddDataRow2", ReplyAction="http://tempuri.org/ILabelGenerator/AddDataRow2Response")]
        bool AddDataRow2(int nJobNumber, string sValue, int nQty, int nStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabelGenerator/PrintLabels", ReplyAction="http://tempuri.org/ILabelGenerator/PrintLabelsResponse")]
        bool PrintLabels();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILabelGeneratorChannel : TestWebPage.LocalService.ILabelGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabelGeneratorClient : System.ServiceModel.ClientBase<TestWebPage.LocalService.ILabelGenerator>, TestWebPage.LocalService.ILabelGenerator {
        
        public LabelGeneratorClient() {
        }
        
        public LabelGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabelGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabelGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabelGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Print(TestWebPage.LocalService.PrinterArea eArea, TestWebPage.LocalService.LabelTypes eLabelType, string[] sColumns, string sTemplate, int nQty, int nStartPos) {
            return base.Channel.Print(eArea, eLabelType, sColumns, sTemplate, nQty, nStartPos);
        }
        
        public int AddPrintJob(TestWebPage.LocalService.PrinterArea eArea, TestWebPage.LocalService.LabelTypes eLabelType, string[] sColumns) {
            return base.Channel.AddPrintJob(eArea, eLabelType, sColumns);
        }
        
        public bool AddDataRow(int nJobNumber, string[] sData) {
            return base.Channel.AddDataRow(nJobNumber, sData);
        }
        
        public bool AddDataRowFromDB(string[] sSerials) {
            return base.Channel.AddDataRowFromDB(sSerials);
        }
        
        public bool AddDataRow2(int nJobNumber, string sValue, int nQty, int nStart) {
            return base.Channel.AddDataRow2(nJobNumber, sValue, nQty, nStart);
        }
        
        public bool PrintLabels() {
            return base.Channel.PrintLabels();
        }
    }
}
